### ISSUE TITLE
Todo Metaissue

### ISSUE THREAD

**Issue by Febbe** [xournalpp/xournalpp#2354]
This issue is a summary of several To-dos found by developers.

 - [ ] Replace path strings with `std::filesystem::path` / `fs::path`
     - [ ] `AudioController`: replace `std::string` with `fs::path`
     - [ ] ...
 - [ ] Replace `fs::path::string` calls with `fs::path::u8string`, if the result is used to display paths.
 - [ ] Create pipeline for msvc or clang for windows based on msvc, because mingw64 is very buggy and does not support all language features of c++11 to c++20 
 - [ ] Release the windows versions build by msvc or clang
 - [ ] Remove `(xournalpp_LDFLAGS ${xournalpp_LDFLAGS} "-Os -s")` and fix the windows pipeline to use the RelWithSize CMAKE flag
