### ISSUE TITLE
Spline interpolation of strokes for better quality rendering

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#2578]
This follows up on #2508 and is related to #2320 (and the associated PR #2512).

**Is your feature request related to a problem? Please describe.**
When drawing fast with a high latency device, we can see the line segments forming the stroke
For instance, this image was generated with my touchpad (in Xournal++)
![segments](https://user-images.githubusercontent.com/17818041/102780709-afe35a00-4396-11eb-8c15-4bc0393eafcb.png)

**Describe the solution you'd like**
Instead of piecewise linear strokes, we could have [splines](https://en.wikipedia.org/wiki/Spline_(mathematics)). From the above input, inkscape generated this spline
![spline](https://user-images.githubusercontent.com/17818041/102780931-15374b00-4397-11eb-991c-7454da871a6e.png)

The algorithm inkscape used here is extremely simple, but there exist way more evolved ones. I'll list some references below.
To make the rendering of those strokes as good as possible, we would need to keep in mind that they are splines. We should allow for spline segments of various degrees in strokes (degree 1 = line segment, degree 2 = quadratic spline segment, degree 3 = cubic spline segment).

**Benefits:**

1. Rendered strokes would be perfectly rescalable (and zooming in to much would not show angular points)
2. This paves the way for optimization by approximation algorithms. Those can drastically reduce the number of spline segments needed to encode a stroke, therefore cutting the file size. Consider those two .svg files contained in this archive [svg.zip](https://github.com/xournalpp/xournalpp/files/5724555/svg.zip). They contain the same sentence (recorded using libinput). One is generated by xournal++ and has size 297 Kib The other has been generated with Krita's calligraphy tool (which is vectorial) and has size 68 Kib. This means a **77%** decrease in file size for a similar (or better...) output quality.
3. This would allow an implementation of smoothing/stabilizing (as in #2320 and #2512) using algorithms like [this one](https://en.wikipedia.org/wiki/Smoothing_spline)

**Road map:** In practice, this breaks into smaller steps

- [ ] Adapt the Stroke class,
- [ ] Extend the .xopp file format.
- [ ] Research further and implement 2.
- [ ] Research further and implement 3.

**Some references:**

- A [library](https://people.math.sc.edu/Burkardt/cpp_src/spline/spline.html) for interpolation/approximation by splines
- Some [piece of code](http://web.archive.org/web/20040625162150/http://www.acm.org/pubs/tog/GraphicsGems/gems/FitCurves.c) implementing something like 2. 
- Krita's [source code](https://invent.kde.org/graphics/krita/-/blob/master/plugins/tools/karbonplugins/tools/CalligraphyTool/KarbonSimplifyPath.cpp) for something like 2. 
- [article](http://caffeineowl.com/graphics/2d/vectorial/cubic2quad01.html) and [article](http://timotheegroleau.com/Flash/articles/cubic_bezier_in_flash.htm) about spline degree reduction (may improve rendering speed, not sure. Need to look at how cairo does things).

I'm happy to work on this, either in #2512 or in a separate PR, but since it touches the .xopp file format, I though this needed discussing first! So, any thoughts?

**Comment by rolandlo** [comment]
Some thoughts:

- We can already create splines of degree <=3 in Xournal++ with the spline tool. We can reuse part of the code (`SplineSegment` class and maybe part of `SplineHandler` class) for spline interpolation/approximation. In future we could make these splines editable and saved as splines (which would be much more efficient). It would take some work to get the standard eraser work on Splines as well, but I think this should be doable (for the future), since one can subdivide splines at any point to get two splines. This is also implemented in the `SplineSegment` class. Other things like scaling/rotating/moving are trivial.
- Schneider's algorithm (that you referenced) is also implemented [here](https://github.com/vicrucann/CurveFitting) in C++ and demonstrated online [here](https://github.com/soswow/fit-curve) (based on JavaScript code)
- Cairo's curve_to is based on cubic spline segments and I wouldn't expect reduction to degree 2 (with 4x to 8x as many segments for good/nearly perfect approximation) to be a good trade-off. 
- The library you mentioned as a reference seems to be used for spline approximation of data (x_i,y_i) modeled by an equation y=f(x)+eps and not suitable for our problem. Similarly with the wikipedia article you mentioned.
- It would be interesting to find out on what Krita's algorithm is based on.

**Comment by bhennion** [comment]
We could also imagine using this: [https://en.wikipedia.org/wiki/Thin_plate_spline](https://en.wikipedia.org/wiki/Thin_plate_spline)

**Comment by rolandlo** [comment]
> ~[](https://en.wikipedia.org/wiki/Thin_plate_spline)~
> **Edit:** Hum... Sorry, I missread what this thing was. I don't think it's usable.

I also don't think it is usable. Maybe stick to Schneider's algorithm for now. A nice demo is [this one](http://paperjs.org/examples/path-simplification/). See also [this explanation](https://stackoverflow.com/questions/27731213/algorithm-for-path-simplification-and-smoothing-of-2d-trajectories)

**Comment by rolandlo** [comment]
Another approach is presented in [this research paper](http://graphics.tudelft.nl/~klaus/papers/shapeAveraging.pdf) (in which the splines we want to construct are called composite cubic Bezier curves).

**Comment by bhennion** [comment]
> Maybe stick to Schneider's algorithm for now. 

The problem with Schneider's algorithm is that it works on a completed stroke. If you try out Krita's calligraphic pen, you'll see the stroke blink when you lift your pen.
One way around this would be to postpone the stroke's rerendering until a full page redraw is done, or the stroke leaves the visible area, or any other such event.

It also means it can't be used as a way of stabilizing the input (which IMO should be dynamic in nature).

> Another approach is presented in [this research paper](http://graphics.tudelft.nl/~klaus/papers/shapeAveraging.pdf) (in which the splines we want to construct are called composite cubic Bezier curves).

Are you sure you posted the right paper? This seems a bit too much and doesn't seem to be (explicitly) talking about Bezier curves.

**Comment by rolandlo** [comment]
Sorry, I posted the wrong like. This is corrected now. 

I think spline interpolation/approximation methods that try to keep the number of control points small can't be completely dynamic. The control points can only be computed after you have drawn/written a stroke part of enough length.

**Comment by bhennion** [comment]
> I think spline interpolation/approximation methods that try to keep the number of control points small can't be completely dynamic. The control points can only be computed after you have drawn/written a stroke part of enough length.

I agree, but one could imagine a two-pass algorithm. The first pass plays a stabilizing role and approximates the last handful of events (say 0.1s worth of event or so). This induces a small but manageable delay in rendering (like any stabilizer). The second pass is computed after the stroke is completed and uses Schneider's algorithm to reduce the number of control points.

The big question would be the cost of the first pass. There seem to exist rather efficient proprietary algorithms doing just that (e.g. [here](https://www.tandfonline.com/doi/abs/10.1080/2151237X.2008.10129260)), but I could not yet locate something opensource.

**Comment by rolandlo** [comment]
Interesting article, looks exactly like what we want (except of some problems with self-intersections). Via [this link](https://pdfslide.net/reader/f/efficient-curve-fitting) everyone can access it freely. I hope the algorithm is not patented. Then we might implement it using the descriptions from the article. As far as I understand the algorithm doesn't need a post-processing stage.

**Comment by bhennion** [comment]
> I hope the algorithm is not patented.

I fear it is patented: there is this (unsubstanciated) [comment](https://stackoverflow.com/questions/27731213/algorithm-for-path-simplification-and-smoothing-of-2d-trajectories#comment104547861_27735435), but also the article itself refers to several patented algorithms by the same author (so this one is most likely patented too).

**Comment by bhennion** [comment]
### Another thing that requires some thinking: how to properly handle the pressure variations.? ###
With the current master, we can obtain things like (set the stroke width to very thick and make a fairly rapid stroke with pressure sensitive device -- here a One by Wacom)
![2020-12-29-Note-14-58](https://user-images.githubusercontent.com/17818041/103289308-2dd2e100-49e7-11eb-8ed2-2f207f485168.png)
We can see that the segments are too long and the pressure variations to big to get a nice result at the end of the stroke.

With splines segments being (on average) longer than line segments (when representing a same stroke), the problem would get worse. There need to be a way

1. of encoding the pressure variations along the splines.
2. of drawing the resulting stroke. 

For 1., several options:
- an array representing the function pressure(length along the spline) or another interpolation ( = a piecewise linear interpolation of the pressure).
- a spline approximation of the same function.
- Use Schneider's approximation on 3D points (x, y, pressure) in the first place.

Quality-wise, the first option is probably enough (I don't think anyone can see a failure of smoothness in the pressure function). It might however not be as cheap (in terms of CPU usage) as we'd think, as computing the length of a spline segment has a cost -- essentially equal to the cost of de Casteljau's algorithm (= SplineSegment::toPointSequence() ). The third option may end up being cheaper.

For 2., I am not sure. Using SplineSegment::toPointSequence() (taking the pressure into account as in [this commit](https://github.com//pull/2512/commits/9d0397ca8b2de115e029c8d86d187085e198d6f4)) and drawing the segments is probably not the best way to go: this kind of job should use hardware acceleration. We could thus rely on Cairo's paths. But Cairo does not offer to draw a spline whose width varies. One possible option (doing both 1. and 2.) would be to store the stroke as its contour (approximated with splines) and simple use cairo_fill(). 

Any ideas?

**Comment by rolandlo** [comment]
My opinion:

For 1. the third option looks like the most promising to me. 
For 2. I would hesitate to use `cairo_fill`, as this may reduce performance significantly. It may be fine for an additional line style as in #2166, but not like a default option which should work well on all devices. I would just draw the segments taking into account the pressure.

**Comment by bhennion** [comment]
I implemented Schneider approximation and Catmull-Rom spline interpolation.
Here is an example of approximations made within xournal++:
![result](https://user-images.githubusercontent.com/17818041/104103361-f515f000-52a1-11eb-98e9-92e891130d27.gif)
In this example, 282 points were replaced by 31 or 33 spline segments (over 9 strokes). In terms of storage, the splines make ~260 * sizeof(double) (or ~275 * sizeof(double)) whereas the original points made ~850 * sizeof(double).
However, the allowed error is probably too big in this example. With a more suited error value, we could hope for a 50% size reduction.
As you can see the Krita-like procedure (Catmul-Rom interpolation -> Schneider apprixomation) does not seem to have any benefit over a single Schneider algorithm, and is probably a waste of cpu usage.

As far as pressure is concerned, I went for the 3D Schneider approximation. It can create artefacts like
![pressure](https://user-images.githubusercontent.com/17818041/104103801-6191ee80-52a4-11eb-970a-162a7da2e5bd.gif)
The original stroke has a fairly even pressure, but the approximated one has noticeable pressure changes. The main reason for those is, I think, that pressure varies way less than the space coordinates. I guess a solution would be to apply a scale factor to the pressure values before applying the algorithm (and reverting this factor afterwards ofc).

**Comment by bhennion** [comment]
Btw, I don't know if this really fits in PR #2512. I can (in due time) make a different PR for this. What do you think?

**Comment by rolandlo** [comment]
Looks pretty great, already! And it has a lot of potential, thinking about editable splines (say if you draw a graph from hand). Your nine strokes have roughly 3 to 4 spline segments per stroke. This would be quite manageable to fine-tune from hand.

About the artifacts I would have recommended you the same idea. It's quite natural to scale the pressure dimension, when it has too little influence on the outcome.

In my opinion it would be better to make a different PR. We can merge the input stabilization and concentrate on the Spline approximation.

**Comment by bhennion** [comment]
> Looks pretty great, already! And it has a lot of potential, thinking about editable splines (say if you draw a graph from hand). Your nine strokes have roughly 3 to 4 spline segments per stroke. This would be quite manageable to fine-tune from hand.

Here are the actual statistics of the above example. I guess it could help in thinking about editable stuff.
```
** Message: 17:33:34.107: Nb points: 61, Schneider segments: 6, CRS splines : 5   ==> S
** Message: 17:33:34.413: Nb points: 19, Schneider segments: 1, CRS splines : 2   ==> vertical bar of p
** Message: 17:33:34.658: Nb points: 21, Schneider segments: 2, CRS splines : 2   ==> belly of p
** Message: 17:33:34.964: Nb points: 20, Schneider segments: 2, CRS splines : 2   ==> l
** Message: 17:33:35.151: Nb points: 10, Schneider segments: 1, CRS splines : 1   ==> i
** Message: 17:33:35.902: Nb points: 81, Schneider segments: 8, CRS splines : 8   ==> ne
** Message: 17:33:36.073: Nb points:  6, Schneider segments: 1, CRS splines : 1   ==> dot of i
** Message: 17:33:36.486: Nb points: 32, Schneider segments: 3, CRS splines : 4   ==> s
** Message: 17:33:36.917: Nb points: 32, Schneider segments: 7, CRS splines : 8   ==> underline
```
Also, for posterity, the maximal error allowed was set to 0.7. So the maximal possible distance between a measure point and the spline is 0.7 (in whatever unit used for the coordinates of points).

> In my opinion it would be better to make a different PR. We can merge the input stabilization and concentrate on the Spline approximation.

Alright!

**Comment by bhennion** [comment]
I've worked a little bit on this. Because it now makes nice pictures, I thought I'd share some:
![boundingBoxes](https://user-images.githubusercontent.com/17818041/105907430-40abf600-6025-11eb-8bb4-a78eaeb58e5f.png)
What you see here is a stroke, approximated by a spline. The bounding boxes of each spline segment and of the total spline are drawn on top. The bounding boxes of the spline segments are computed (in xournal++) using simple closed formulas, so it's probably faster than the previous "test all points" strategy (didn't benchmark though).

We can also compute the intersection of a spline with a line:
![Screenshot_20210126_222949](https://user-images.githubusercontent.com/17818041/105908248-45bd7500-6026-11eb-942a-4f8d4be5efd3.png)
This will come in handy when we'll adapt the (for some reason square shaped) eraser.
