### ISSUE TITLE
Better Presentation Mode

### ISSUE THREAD

**Issue by forgottosave** [xournalpp/xournalpp#4456]
## Description
A feature *Xournal++* is really lacking is a good **presentation mode**. The current mode does nothing but adjust the zoom.
This issue has already been addressed in PR #2408, but it is outdated by almost *1000* commits and hasn't had any activity for a long time.
This thread here is meant to discuss & keep track of suggestions & implementations regarding this problem.

## TODOs
A collection of ideas that have to be discussed & implemented for a good presentation mode:
- [ ] fix the page zoom and scroll to fit window
- [ ] stop rendering other pages than the selected one
- [ ] add some sort of laser pointer tool
- [ ] automatically hide the sidebar, menubar, etc.

#### Issues
- #2117
- #4340 
#### PRs
- #2408 
- #4434

**Comment by forgottosave** [comment]
I'd love to work on some of these issues, as soon as they are approved to help build a better presentation mode :)

**Comment by rolandlo** [comment]
I think the laser pointer tool (see #1778 and #1822), although important, is somewhat independent from the rest. The timer for a presentation mode would be nice to have, but not the first priority. The rest of the TODO's look all very desirable and important.

**Comment by mjg** [comment]
Maybe it's good to agree on what purpose this mode serves, or how modes work in general. For example, shown/hidden elements can be adjusted in config:
```
<property name="presentationHideElements" value="mainMenubar,sidebarContents"/>
```
I have not checked whether leaving the mode resets those to the previous state or unhides them. I guess the real question is: Do we switch between modes (one being "default"), or can one use them together or even no mode at all?

E.g., "fullscreen" sounds as if it does just that (switch to fullscreen), when indeed it is a mode.

It might be worthwhile to think about modes as a preset of several things (fullscreen or not, fixed canvas or scrolling, zoom fixed at full page or some default, sidebars to be shown, maybe even the UI layout). This would allow everyone to have "their" presentation mode. It also means that missing presentation functionality should be made dependent on a setting, not the mode.

**Comment by forgottosave** [comment]
In my current workin-progrees for this issue I implement it, so that the menu-hiding is actually dependent on the settings.
But I have to agree with you (@mjg), we could generalize it to every mode being a preset of those listed things. There could be default presets for the default- and presentation-mode (and other important ones) for anyone not wanting to configure anything. But it would also leave the option of setting additional custom presets as well.
What do others (especially maintainers) think of this idea?

**Comment by forgottosave** [comment]
Note that for implementing the different custom presets we would probably have to do some file format changes (which as I understand is at a major reconstruction right now and not open for such feature changes?), to store the custom presets for all modes.

But I think the implementation for the predefined modes could be done without file changes, leaving the possibility for additional custom modes (or changes to the predefined states) open for a future feature.

**Comment by bhennion** [comment]
Here are other presentation mode related issues needing a fix:

- #2943
- #2847
- #2773 #2025
- #2621
- #1733

**Comment by forgottosave** [comment]
I'll add them to the TODO-list in the PR description.
Some of those issues get fixed by my PRs already. I'll maybe have a look into some other ones as well.

**Comment by forgottosave** [comment]
Most of the open issues are currently available in the branch [feature-branch-230110](https://github.com/forgottosave/xournalpp/tree/feature-branch-230110) on my fork of this project, including the customizable preset view modes, improved page rendering and zoom updates. There you can see how everything works combined.
